sct:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sct
    username: root
    password: 123456
  # 文件路径 示例（ Windows配置 D:/sct/uploadPath，Linux配置 /home/sct/uploadPath）
  profile: D:/sct_msq_upload/sct/upload
  s3:
    endpoint:
    region: auto
    access-key-id:
    secret-access-key:
    bucket-name:
    public-url:
    object-prefix:
    path-style-access: true
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
# 文件存储配置
oss:
  type: 0 # 0：本地存储，1：S3存储